[build]
  publish = "."  # файли в корені
  command = ""  # без збірки

[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    buildDir = "."  # файли в корені
    baseUrl = "https://vacleaner.pp.ua"  # твоя URL
    filePath = "sitemap.xml"  # шлях до карти

# Редирект для сайтмапу (але він тут не обов'язковий)
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

# Встановлюємо правильні заголовки для сайтмапу
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Encoding = "identity"  # Вимикаємо Brotli (br)
