import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.112.0";
import { DEFAULT_CATALOG, DEFAULT_SLOTS, rentalDays, rentalBase } from "https://raw.githubusercontent.com/VAcleaner-washing/pl/70d01a4ccb211b1a8258a93ee8921744637e8ce2/supabase/functions/vacleaner-admin-bookings-v3/config.ts";
import { discountInfo } from "https://raw.githubusercontent.com/VAcleaner-washing/pl/70d01a4ccb211b1a8258a93ee8921744637e8ce2/supabase/functions/vacleaner-admin-bookings-v3/pricing.mjs";
import { settlementFromBooking } from "https://raw.githubusercontent.com/VAcleaner-washing/pl/70d01a4ccb211b1a8258a93ee8921744637e8ce2/supabase/functions/vacleaner-admin-bookings-v3/settlement.mjs";

const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type, x-client-info","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json; charset=utf-8"}});
const validBookingId=(value:unknown)=>/^[0-9a-f-]{36}$/i.test(String(value??""));
const dateValue=(value:unknown)=>typeof value==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(value)?value:"";
const validTime=(value:unknown)=>typeof value==="string"&&/^\d{2}:\d{2}$/.test(value);
const cleanInt=(value:unknown,max=100000)=>Math.max(0,Math.min(max,Math.floor(Number(value)||0)));
const defaultCatalog:any=structuredClone(DEFAULT_CATALOG);
const defaultSlots:any=structuredClone(DEFAULT_SLOTS);
function mergeCatalog(value:any){const out:any=structuredClone(defaultCatalog);if(!value||typeof value!=="object")return out;const pp=Number(value.puzziPacketPrice);if(Number.isFinite(pp)&&pp>=0)out.puzziPacketPrice=pp;for(const [code,item] of Object.entries(value.products||{})){if(item&&typeof item==="object")out.products[code]={...(out.products[code]||{}),...(item as Record<string,any>)}}for(const [code,item] of Object.entries(value.extras||{})){if(item&&typeof item==="object")out.extras[code]={...(out.extras[code]||{}),...(item as Record<string,any>)}}return out}
function normalizeSlots(value:any){const out={morningStart:String(value?.morningStart??defaultSlots.morningStart),morningEnd:String(value?.morningEnd??defaultSlots.morningEnd),eveningStart:String(value?.eveningStart??defaultSlots.eveningStart),eveningEnd:String(value?.eveningEnd??defaultSlots.eveningEnd)};return Object.values(out).every(validTime)?out:structuredClone(defaultSlots)}
function inWindow(time:string,window:string,slots:any){return window==="morning"?time>=slots.morningStart&&time<=slots.morningEnd:time>=slots.eveningStart&&time<=slots.eveningEnd}
function resourcePayload(product:any){return Object.entries(product?.resources||{}).map(([resource_code,quantity])=>({resource_code,quantity:Number(quantity||0)})).filter(row=>row.quantity>0)}
async function tagAudit(supabase:any,bookingId:string,actorId:string,since:string){const {error}=await supabase.from("vacleaner_booking_audit").update({actor_id:actorId,source:"edge:extend_rental"}).eq("booking_id",bookingId).is("actor_id",null).gte("created_at",since);if(error)console.warn("audit_tag_failed",error.message)}

Deno.serve(async(request:Request)=>{if(request.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});if(request.method!=="POST")return json({error:"method_not_allowed"},405);try{
 const supabaseUrl=Deno.env.get("SUPABASE_URL"),serviceRoleKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),token=(request.headers.get("Authorization")??"").replace(/^Bearer\s+/i,"");if(!supabaseUrl||!serviceRoleKey||!token)return json({error:"unauthorized"},401);
 const supabase=createClient(supabaseUrl,serviceRoleKey,{auth:{persistSession:false,autoRefreshToken:false}});const {data:userData,error:userError}=await supabase.auth.getUser(token);if(userError||!userData.user)return json({error:"unauthorized"},401);const {data:admin}=await supabase.from("admin_users").select("user_id").eq("user_id",userData.user.id).maybeSingle();if(!admin)return json({error:"forbidden"},403);
 const body=await request.json() as Record<string,any>,bookingId=String(body.bookingId||"");if(!validBookingId(bookingId))return json({error:"invalid_booking"},400);
 const [{data:current,error:currentError},{data:settings,error:settingsError}]=await Promise.all([supabase.from("vacleaner_bookings").select("*").eq("id",bookingId).single(),supabase.from("vacleaner_settings").select("key,value").in("key",["catalog","booking_slots"])]);if(currentError||!current)return json({error:"invalid_booking"},404);if(settingsError)throw settingsError;if(String(current.status||"")!=="issued")return json({error:"extension_only_for_issued"},409);
 const settingsMap=Object.fromEntries((settings||[]).map((row:any)=>[row.key,row.value])),catalog=mergeCatalog(settingsMap.catalog),slots=normalizeSlots(settingsMap.booking_slots),product=catalog.products?.[String(current.product_code||"")];if(!product)return json({error:"invalid_product"},400);
 const extras=current.extras&&typeof current.extras==="object"?current.extras:{},oldReturnTime=String(extras.return_time||(current.return_window==="morning"?slots.morningEnd:slots.eveningEnd)),returnDate=dateValue(body.returnDate),returnWindow=body.returnWindow==="morning"?"morning":"evening",returnTime=String(body.returnTime||(returnWindow==="morning"?slots.morningEnd:slots.eveningEnd));if(!returnDate||!validTime(returnTime)||!inWindow(returnTime,returnWindow,slots))return json({error:"invalid_exact_time"},400);if(`${returnDate}T${returnTime}`<=`${current.return_date}T${oldReturnTime}`)return json({error:"invalid_extension"},409);
 const pickupWindow=current.pickup_window==="evening"?"evening":"morning",pickupTime=String(extras.pickup_time||(pickupWindow==="morning"?slots.morningStart:slots.eveningStart)),days=rentalDays(String(current.start_date),returnDate,pickupWindow,returnWindow);if(days<1||days>14)return json({error:"invalid_rental_period"},400);
 const rawBase=rentalBase(product,String(current.start_date),returnDate,pickupWindow,returnWindow),discount=discountInfo({},rawBase,extras),oldBaseAmount=Math.max(0,Number(current.base_amount||0)),newBaseAmount=Math.max(0,Number(discount.baseAmount||0)),now=new Date().toISOString(),history=Array.isArray(extras.rental_extensions)?extras.rental_extensions.slice(-9):[],extension={extended_at:now,old_return_date:String(current.return_date),old_return_window:String(current.return_window||"evening"),old_return_time:oldReturnTime,new_return_date:returnDate,new_return_window:returnWindow,new_return_time:returnTime,old_base_amount:oldBaseAmount,new_base_amount:newBaseAmount,added_rental_amount:Math.max(0,newBaseAmount-oldBaseAmount),deposit_amount_preserved:Math.max(0,Number(current.deposit_amount||0)),deposit_paid_preserved:current.deposit_paid===true};
 const nextExtras:any={...extras,return_time:returnTime,slot_config:slots,base_before_discount:rawBase,discount:{type:discount.type,percent:discount.percent,amount:discount.amount,source:discount.source,reason:discount.source==="manual"?discount.manualReason:""},manual_discount:discount.manualType==="none"?null:{type:discount.manualType,value:discount.manualValue,amount:discount.manualAmount,reason:discount.manualReason},rental_extensions:[...history,extension]},finance=settlementFromBooking({...current,base_amount:newBaseAmount,extras:nextExtras},catalog,defaultCatalog);if(extras.settlement&&typeof extras.settlement==="object")nextExtras.settlement={...extras.settlement,prepayment_amount:finance.prepaymentAmount,deposit_amount:finance.depositPaid?finance.securityDeposit:0,received_amount:finance.receivedAmount,expenses_amount:finance.totalAmount,refund_amount:finance.refundAmount,due_amount:finance.dueAmount,completed:false,completed_at:null,calculated_at:now};
 const actionStartedAt=new Date(Date.now()-1500).toISOString();const {data:reserved,error:rpcError}=await supabase.rpc("vacleaner_apply_reservation",{p_booking_id:bookingId,p_start_date:String(current.start_date),p_return_date:returnDate,p_pickup_window:pickupWindow,p_return_window:returnWindow,p_start_at:`${current.start_date}T${pickupTime}:00.000Z`,p_end_at:`${returnDate}T${returnTime}:00.000Z`,p_rental_days:days,p_resources:resourcePayload(product),p_target_status:"issued",p_hold_expires_at:null});if(rpcError){if(String(rpcError.message||"").includes("inventory_conflict"))return json({error:"inventory_conflict"},409);throw rpcError}void reserved;
 const {data,error}=await supabase.from("vacleaner_bookings").update({extras:nextExtras,base_amount:newBaseAmount,extras_amount:finance.totalExtras,total_amount:finance.totalAmount,updated_at:now}).eq("id",bookingId).select("*").single();if(error||!data)throw error||new Error("update_failed");await tagAudit(supabase,bookingId,userData.user.id,actionStartedAt);return json({booking:data,finance,extension:{addedRentalAmount:extension.added_rental_amount,oldBaseAmount,newBaseAmount,depositAmount:extension.deposit_amount_preserved}});
 }catch(error){const message=error instanceof Error?error.message:"service_error";console.error("vacleaner-extend-rental-v1",message);if(message.includes("inventory_conflict"))return json({error:"inventory_conflict"},409);return json({error:"service_error"},500)}});
