import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.112.0";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type, x-client-info","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json; charset=utf-8"}});
const validUuid=(v:unknown)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||""));
const normalizePhone=(v:unknown)=>{const d=String(v||"").replace(/\D/g,"");if(d.length===10&&d.startsWith("0"))return `+38${d}`;if(d.length===12&&d.startsWith("380"))return `+${d}`;return ""};
const dayNumber=(v:string)=>{const t=Date.parse(String(v||"").slice(0,10)+"T12:00:00Z");return Number.isFinite(t)?Math.floor(t/86400000):NaN};
const rentalDays=(a:string,z:string,p='morning',r='evening')=>{const s=dayNumber(a),e=dayNumber(z);if(!Number.isFinite(s)||!Number.isFinite(e)||e<s)return 0;const po=p==='evening'?1:0,ro=r==='evening'?1:0,days=e-s;return days===0?(ro>po?1:0):days+(ro>po?1:0)};
const paidDates=(a:string,z:string,p='morning',r='evening')=>{const n=rentalDays(a,z,p,r),s=dayNumber(a);if(!n||!Number.isFinite(s))return[];return Array.from({length:n},(_,i)=>new Date((s+i)*86400000+12*3600000).toISOString().slice(0,10))};
const promoAmount=(raw:number,c:any)=>c?.discount_type==='fixed'?Math.min(raw,Math.max(0,Math.round(Number(c.discount_value)||0))):Math.min(raw,Math.round(raw*Math.min(100,Math.max(0,Number(c?.discount_value)||0))/100));
function discountState(raw:number,extras:any,promo:any=null){
  const base=Math.max(0,Number(raw)||0),lp=[0,5,10].includes(Number(extras?.loyalty?.percent))?Number(extras.loyalty.percent):0,loyalty=Math.round(base*lp/100);
  const m=extras?.manual_discount||{},mt=m.type==='fixed'?'fixed':m.type==='percent'?'percent':'none',mv=mt==='percent'&&[5,10].includes(Number(m.value))?Number(m.value):mt==='fixed'?Math.max(0,Math.round(Number(m.value)||0)):0,manual=mt==='fixed'?Math.min(base,mv):mt==='percent'?Math.min(base,Math.round(base*mv/100)):0;
  const pa=promo?promoAmount(base,promo):0;let source=loyalty?'loyalty':'none',type=loyalty?'percent':'none',percent=lp,amount=loyalty;
  if(pa>amount){source='promo';type=promo.discount_type==='fixed'?'fixed':'percent';percent=type==='percent'?Number(promo.discount_value||0):0;amount=pa}
  if(manual>amount){source='manual';type=mt;percent=mt==='percent'?mv:0;amount=manual}
  return{source,type,percent,amount,baseAmount:Math.max(0,base-amount),reason:source==='manual'?String(m.reason||''):''};
}
async function availablePromo(db:any,booking:any){
  const phone=normalizePhone(booking.customer_phone);if(!phone)return null;
  const {data:codes,error:ce}=await db.from("vacleaner_promo_codes").select("id,campaign_id,code,customer_phone,active,expires_at,usage_limit,activated_at,activation_source").eq("customer_phone",phone).eq("active",true).not("activated_at","is",null).order("activated_at",{ascending:false}).limit(20);if(ce)throw ce;if(!codes?.length)return null;
  const ids=[...new Set(codes.map((x:any)=>String(x.campaign_id||"")).filter(Boolean))];const [{data:campaigns,error:cge},{data:redemptions,error:re},{data:history,error:he}]=await Promise.all([
    db.from("vacleaner_campaigns").select("id,name,campaign_type,status,discount_type,discount_value,dormant_days,min_completed_orders,allowed_product_codes,allowed_weekdays,usage_limit_total,usage_limit_per_customer,starts_at,ends_at").in("id",ids),
    db.from("vacleaner_promo_redemptions").select("promo_code_id,campaign_id,customer_phone,booking_id").in("campaign_id",ids),
    db.from("vacleaner_bookings").select("id,status,hold_expires_at,start_date,return_date,completed_at,created_at").eq("customer_phone",phone).order("created_at",{ascending:false}).limit(200)
  ]);if(cge||re||he)throw cge||re||he;
  const completed=(history||[]).filter((x:any)=>x.status==='completed'),last=completed.reduce((m:string,x:any)=>{const v=String(x.completed_at||x.return_date||x.start_date||'').slice(0,10);return v>m?v:m},''),activeOther=(history||[]).some((x:any)=>String(x.id)!==String(booking.id)&&["pending","waiting_payment","confirmed","issued"].includes(String(x.status)));
  const raw=Math.max(0,Number(booking.extras?.base_before_discount||booking.base_amount||0)),now=Date.now(),candidates:any[]=[];
  for(const code of codes){const c=(campaigns||[]).find((x:any)=>String(x.id)===String(code.campaign_id));if(!c||!["return","personal"].includes(String(c.campaign_type||""))||c.status!=="active")continue;const starts=c.starts_at?new Date(c.starts_at).getTime():0,ends=c.ends_at?new Date(c.ends_at).getTime():0,codeEnd=code.expires_at?new Date(code.expires_at).getTime():0;if((starts&&starts>now)||(ends&&ends<=now)||(codeEnd&&codeEnd<=now))continue;
    const codeUses=(redemptions||[]).filter((x:any)=>String(x.promo_code_id)===String(code.id)).length,customerUses=(redemptions||[]).filter((x:any)=>String(x.campaign_id)===String(c.id)&&normalizePhone(x.customer_phone)===phone).length,campaignUses=(redemptions||[]).filter((x:any)=>String(x.campaign_id)===String(c.id)).length;if(codeUses>=Math.max(1,Number(code.usage_limit||1))||customerUses>=Math.max(1,Number(c.usage_limit_per_customer||1))||(c.usage_limit_total&&campaignUses>=Number(c.usage_limit_total)))continue;
    if(completed.length<Number(c.min_completed_orders||0))continue;if(c.campaign_type==='return'){if(!last||activeOther)continue;const cutoff=now-Math.max(1,Number(c.dormant_days||180))*86400000;if(new Date(last+'T12:00:00Z').getTime()>cutoff)continue}
    const products=Array.isArray(c.allowed_product_codes)?c.allowed_product_codes.map(String):[];if(products.length&&!products.includes(String(booking.product_code||'')))continue;const weekdays=Array.isArray(c.allowed_weekdays)?c.allowed_weekdays.map(Number):[];if(weekdays.length){const dates=paidDates(String(booking.start_date||''),String(booking.return_date||''),booking.pickup_window||'morning',booking.return_window||'evening');if(!dates.length||dates.some(d=>!weekdays.includes(new Date(d+'T12:00:00Z').getUTCDay())))continue}
    candidates.push({...c,promoCodeId:code.id,code:String(code.code||''),expiresAt:code.expires_at,activatedAt:code.activated_at,activationSource:code.activation_source,amount:promoAmount(raw,c)});
  }
  candidates.sort((a,b)=>b.amount-a.amount);return candidates[0]||null;
}
const publicPromo=(p:any)=>p?{code:p.code,campaignId:String(p.id),campaignName:String(p.name||'Персональний бонус'),campaignType:String(p.campaign_type||''),discountType:p.discount_type==='fixed'?'fixed':'percent',discountValue:Number(p.discount_value||0),expiresAt:p.expiresAt||null,activatedAt:p.activatedAt||null,activationSource:p.activationSource||null,eligible:true}:null;

Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'method_not_allowed'},405);try{
  const url=Deno.env.get('SUPABASE_URL'),service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'),token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');if(!url||!service||!token)return json({error:'unauthorized'},401);const db=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}}),{data:u,error:ue}=await db.auth.getUser(token);if(ue||!u.user)return json({error:'unauthorized'},401);const {data:admin,error:ae}=await db.from('vacleaner_admin_users').select('user_id').eq('user_id',u.user.id).maybeSingle();if(ae)throw ae;if(!admin)return json({error:'forbidden'},403);
  const body=await req.json() as any,action=String(body.action||''),bookingId=String(body.bookingId||'');if(!validUuid(bookingId))return json({error:'invalid_booking'},400);const {data:b,error:be}=await db.from('vacleaner_bookings').select('*').eq('id',bookingId).maybeSingle();if(be)throw be;if(!b)return json({error:'invalid_booking'},404);if(!['pending','waiting_payment','confirmed'].includes(String(b.status||'')))return json({error:'invalid_transition'},409);const extras=b.extras&&typeof b.extras==='object'?b.extras:{};
  if(action==='status'){const attached=extras?.promo||null,available=attached?null:await availablePromo(db,b);return json({attachedPromo:attached,availablePromo:publicPromo(available)})}
  if(action==='detach'){if(!extras?.promo)return json({booking:b,detached:false});const raw=Math.max(0,Number(extras?.base_before_discount||0)||(Number(b.base_amount||0)+Number(extras?.discount?.amount||0))),state=discountState(raw,extras,null),next={...extras,promo:null,discount:{type:state.type,percent:state.percent,amount:state.amount,source:state.source,reason:state.reason},base_before_discount:raw},total=state.baseAmount+Math.max(0,Number(b.extras_amount||0))+Math.max(0,Number(b.delivery_amount||0));const {error}=await db.rpc('vacleaner_admin_detach_booking_promo',{p_booking_id:bookingId,p_extras:next,p_base_amount:state.baseAmount,p_total_amount:total});if(error)throw error;const {data:saved}=await db.from('vacleaner_bookings').select('*').eq('id',bookingId).single();return json({booking:saved,detached:true})}
  if(action==='attach'){if(extras?.promo)return json({error:'booking_promo_already_attached'},409);const promo=await availablePromo(db,b);if(!promo)return json({error:'promo_unavailable'},409);const raw=Math.max(0,Number(extras?.base_before_discount||b.base_amount||0)),state=discountState(raw,extras,promo);if(state.source!=='promo'||state.amount<=0)return json({error:'promo_not_best_discount'},409);const promoExtra={code:promo.code,campaign_id:String(promo.id),campaign_name:String(promo.name||'Персональний бонус'),campaign_type:String(promo.campaign_type||''),discount_type:promo.discount_type==='fixed'?'fixed':'percent',discount_value:Number(promo.discount_value||0),applied:true},next={...extras,promo:promoExtra,discount:{type:state.type,percent:state.percent,amount:state.amount,source:'promo',reason:''},base_before_discount:raw},total=state.baseAmount+Math.max(0,Number(b.extras_amount||0))+Math.max(0,Number(b.delivery_amount||0));const {error}=await db.rpc('vacleaner_admin_attach_booking_promo',{p_booking_id:bookingId,p_promo_code_id:promo.promoCodeId,p_campaign_id:promo.id,p_customer_phone:normalizePhone(b.customer_phone),p_discount_amount:state.amount,p_base_before_discount:raw,p_extras:next,p_base_amount:state.baseAmount,p_total_amount:total});if(error)return json({error:'promo_unavailable'},409);const {data:saved}=await db.from('vacleaner_bookings').select('*').eq('id',bookingId).single();return json({booking:saved,attached:true,promo:publicPromo(promo)})}
  return json({error:'invalid_action'},400);
}catch(e){console.error('vacleaner-booking-promo-v1',e instanceof Error?e.message:e);return json({error:'service_error'},500)}});
