import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const root=process.cwd();
const release=JSON.parse(fs.readFileSync(path.join(root,'release.json'),'utf8'));
const configPath=path.join(root,'config','vacleaner.json');
const raw=fs.readFileSync(configPath,'utf8');
const config=JSON.parse(raw);
const hash=crypto.createHash('sha256').update(raw).digest('hex').slice(0,16);
const compact=JSON.stringify(config);
const browser=`(()=>{'use strict';const VERSION=${JSON.stringify(String(release.version))};const SOURCE_HASH=${JSON.stringify(hash)};const config=${compact};const {images,catalog,depositRules,slots}=config;const {products,extras}=catalog;const productAliases={};Object.entries(products).forEach(([code,item])=>[item.label,item.shortLabel,...(item.aliases||[])].filter(Boolean).forEach(label=>{productAliases[label]=code}));const extraAliases={};Object.entries(extras).forEach(([code,item])=>[item.label,...(item.aliases||[])].filter(Boolean).forEach(label=>{extraAliases[label]=code}));const clone=value=>typeof structuredClone==='function'?structuredClone(value):JSON.parse(JSON.stringify(value));const productMeta=code=>products[code]||null;const productImages=code=>(productMeta(code)?.imageKeys||['puzzi']).map(key=>images[key]).filter(Boolean);const depositGroup=code=>productMeta(String(code||''))?.depositGroup||'oneUnit';const rentalDays=(startDate,returnDate,pickupWindow='morning',returnWindow='evening')=>{if(!startDate||!returnDate)return 0;const start=Date.parse(String(startDate).slice(0,10)+'T12:00:00Z'),finish=Date.parse(String(returnDate).slice(0,10)+'T12:00:00Z');if(!Number.isFinite(start)||!Number.isFinite(finish)||finish<start)return 0;const calendarDays=Math.round((finish-start)/86400000),pickupOrder=pickupWindow==='evening'?1:0,returnOrder=returnWindow==='evening'?1:0;return calendarDays===0?(returnOrder>pickupOrder?1:0):calendarDays+(returnOrder>pickupOrder?1:0)};const isWeekendDeposit=(startDate,returnDate,pickupWindow='morning',returnWindow='evening')=>{const count=rentalDays(startDate,returnDate,pickupWindow,returnWindow);if(count<2)return false;const start=Date.parse(String(startDate).slice(0,10)+'T12:00:00Z');for(let index=0;index<count;index+=1){const day=new Date(start+index*86400000).getUTCDay();if(day===0||day===6)return true}return false};window.VACLEANER_CORE=Object.freeze({VERSION,version:VERSION,SOURCE_HASH,sourceHash:SOURCE_HASH,config,images,products,extras,catalog,depositRules,slots,productAliases,extraAliases,clone,productMeta,productImages,depositGroup,rentalDays,isWeekendDeposit});})();\n`;
fs.writeFileSync(path.join(root,'assets','vacleaner-core.js'),browser);
const shared=`// GENERATED from config/vacleaner.json. Do not edit by hand.\nexport const VACLEANER_RELEASE_VERSION=${JSON.stringify(String(release.version))};\nexport const VACLEANER_SOURCE_HASH=${JSON.stringify(hash)};\nexport const VACLEANER_CONFIG=${JSON.stringify(config)} as const;\nexport const DEFAULT_SLOTS=structuredClone(VACLEANER_CONFIG.slots);\nexport const DEFAULT_DEPOSIT_RULES=structuredClone(VACLEANER_CONFIG.depositRules);\nexport const DEFAULT_CATALOG=structuredClone(VACLEANER_CONFIG.catalog);\nexport function rentalDays(startDate:string,returnDate:string,pickupWindow='morning',returnWindow='evening'){if(!startDate||!returnDate)return 0;const start=Date.parse(String(startDate).slice(0,10)+'T12:00:00Z'),finish=Date.parse(String(returnDate).slice(0,10)+'T12:00:00Z');if(!Number.isFinite(start)||!Number.isFinite(finish)||finish<start)return 0;const calendarDays=Math.round((finish-start)/86400000),pickupOrder=pickupWindow==='evening'?1:0,returnOrder=returnWindow==='evening'?1:0;return calendarDays===0?(returnOrder>pickupOrder?1:0):calendarDays+(returnOrder>pickupOrder?1:0)}\nexport function isWeekendDeposit(startDate:string,returnDate:string,pickupWindow='morning',returnWindow='evening'){const count=rentalDays(startDate,returnDate,pickupWindow,returnWindow);if(count<2)return false;const start=Date.parse(String(startDate).slice(0,10)+'T12:00:00Z');for(let index=0;index<count;index+=1){const day=new Date(start+index*86400000).getUTCDay();if(day===0||day===6)return true}return false}\n`;
for(const name of ['vacleaner-settings','vacleaner-booking-v5','vacleaner-admin-bookings-v3']){
 const dir=path.join(root,'supabase','functions',name);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'config.ts'),shared);
}
console.log(`Generated shared VAcleaner config ${hash}`);
