#!/usr/bin/env python3
from pathlib import Path
from playwright.sync_api import sync_playwright
import importlib.util, os, sys
ROOT=Path(__file__).resolve().parents[1]
spec=importlib.util.spec_from_file_location('pwaqa',ROOT/'scripts/pwa_visual_qa.py')
mod=importlib.util.module_from_spec(spec);sys.modules['pwaqa']=mod;spec.loader.exec_module(mod)
fail=[]
def check(c,label):
 print(('PASS' if c else 'FAIL')+': '+label)
 if not c: fail.append(label)
with sync_playwright() as p:
 opts={'headless':True,'args':['--no-sandbox']}
 executable=os.environ.get('PLAYWRIGHT_CHROMIUM_EXECUTABLE')
 if executable: opts['executable_path']=executable
 elif Path('/usr/bin/chromium').exists(): opts['executable_path']='/usr/bin/chromium'
 browser=p.chromium.launch(**opts)
 for w in (320,390,430):
  page=mod.render_page(browser,w,844,authenticated=True,standalone=True)
  page.evaluate("document.documentElement.style.setProperty('--pwa-safe-top','47px');document.documentElement.style.setProperty('--pwa-safe-bottom','34px')")
  page.wait_for_timeout(120)
  if page.locator('.pwa-update-prompt').count():page.locator('.pwa-update-later').click()
  mod.open_mobile_view(page,'bookings');page.wait_for_timeout(100)
  card=page.locator('.booking-row').first
  rail=card.evaluate("el=>({w:getComputedStyle(el,'::before').width,bg:getComputedStyle(el,'::before').backgroundImage})")
  check(rail['w']=='4px',f'{w}: booking cards have 4px semantic status rail')
  check(mod.no_overflow(page),f'{w}: bookings V4 no overflow')
  page.locator('.booking-card [data-client-card]').first.evaluate('el=>el.click()');page.wait_for_selector('#clientEditor');page.wait_for_timeout(80)
  check(page.locator('.glass-client-actions').count()==0,f'{w}: no duplicate glass-injected client action bar remains')
  actions=page.locator('#clientEditor .client-quick-actions')
  check(actions.count()==1 and page.locator('#clientEditor.client-card-v245').count()==1,f'{w}: client quick actions use the v4.2.45 priority layer')
  visible_children=page.locator('#clientEditor .client-quick-actions-v245 > *:visible')
  check(visible_children.count()>=3,f'{w}: frequent client actions remain visible without referral duplication')
  geometries=visible_children.evaluate_all("els=>els.map(el=>{const r=el.getBoundingClientRect();return{w:r.width,h:r.height,scrollWidth:el.scrollWidth,clientWidth:el.clientWidth}})")
  check(bool(geometries) and all(g['h']>=42 for g in geometries),f'{w}: client actions keep usable tap height')
  check(all(g['scrollWidth']<=g['clientWidth']+1 for g in geometries),f'{w}: Telegram and other action labels do not clip')
  check(page.locator('#clientEditor .client-referral-quick').count()==0 and page.locator('#clientOpenReferralDetails').count()==1,f'{w}: referral stays reachable inside benefits without competing with New rental')
  check(mod.no_overflow(page),f'{w}: client card no horizontal overflow')
  summary_cols=page.locator('#clientEditor .client-editor-summary').evaluate("el=>getComputedStyle(el).gridTemplateColumns.split(' ').length") if page.locator('#clientEditor .client-editor-summary').count() else 0
  check(summary_cols==2,f'{w}: client KPIs stay compact as a 2x2 summary')
  if w==390:
   page.screenshot(path=str(ROOT/'glass-test-results/client-card-glass-v4-390.png'),full_page=True)
   nav_to_booking=page.locator('#clientOpenActiveBooking,#clientOpenLastBooking').first
   if nav_to_booking.count():
    nav_to_booking.click();page.wait_for_selector('.detail');page.wait_for_timeout(60)
    check('До картки' in page.locator('.detail .back').inner_text(),f'{w}: booking opened from client keeps an explicit return path')
    page.locator('.detail .back').click();page.wait_for_selector('#clientEditor');page.wait_for_timeout(60)
    check(page.locator('#clientEditor').count()==1,f'{w}: detail back restores the client card instead of losing CRM context')
  page.locator('#clientEditor [data-close]').first.click();page.wait_for_timeout(50)
  page.locator('#mobileNewBooking').click();page.wait_for_selector('#bookingForm');page.wait_for_timeout(80)
  check(page.locator('#bookingForm .mobile-booking-progress span').count()==4,f'{w}: new booking keeps four explicit steps')
  check(mod.no_overflow(page),f'{w}: new booking glass sheet no horizontal overflow')
  modal_box=page.locator('.modal-card:has(#bookingForm)').bounding_box()
  check(modal_box is not None and modal_box['x']>=0 and modal_box['x']+modal_box['width']<=w+1,f'{w}: booking sheet stays inside viewport')
  if w==390: page.screenshot(path=str(ROOT/'glass-test-results/new-booking-glass-v4-390.png'),full_page=True)
  page.locator('#bookingForm [data-close]').first.click();page.wait_for_timeout(50)
  mod.open_mobile_view(page,'upcoming');page.wait_for_timeout(80)
  check(page.locator('.upcoming-row [data-client-card]').count()==0,f'{w}: upcoming customer is not directly clickable')
  check(page.locator('.upcoming-row .upcoming-client-info a[href^="tel:"]').count()>=1,f'{w}: upcoming phone remains callable')
  page.locator('.upcoming-row .upcoming-client-info strong').first.click();page.wait_for_timeout(30)
  check(page.locator('#clientEditor').count()==0 and page.locator('.detail').count()==0,f'{w}: customer name tap stays on Upcoming')
  mod.open_mobile_view(page,'calendar');page.wait_for_timeout(80)
  check(page.locator('.calendar-grid .slot').count()>0,f'{w}: calendar slots rendered')
  check(mod.no_overflow(page),f'{w}: calendar V4 no overflow')
  mod.open_mobile_view(page,'analytics');page.wait_for_timeout(80)
  toolbar=page.locator('.analytics-toolbar').first
  material=toolbar.evaluate("el=>{const s=getComputedStyle(el);return {bg:s.backgroundColor,img:s.backgroundImage,border:s.borderTopWidth,shadow:s.boxShadow}}")
  check(material['bg']=='rgba(0, 0, 0, 0)' and material['img']=='none',f'{w}: analytics toolbar has no inherited opaque strip')
  check(material['border']=='0px' and material['shadow']=='none',f'{w}: analytics toolbar has no inherited border or shadow')
  check(page.locator('.analytics-periods .chip').count()==5,f'{w}: five analytics period controls remain visible')
  page.locator('[data-analytics-period="month"]').click()
  check(page.locator('#analyticsMonthPicker').count()==1,f'{w}: premium month picker trigger appears')
  check(page.locator('#analyticsMonth').count()==0,f'{w}: native month select is removed')
  check(page.locator('.analytics-calendar-picker').count()==1,f'{w}: calendar period picker appears')
  check(mod.no_overflow(page),f'{w}: analytics toolbar fix keeps viewport stable')
  if w==390: page.screenshot(path=str(ROOT/'glass-test-results/analytics-toolbar-fix-390.png'),full_page=True)
  page.close()
 for w,h in ((1648,927),(1440,900),(1280,800),(1024,768)):
  page=mod.render_page(browser,w,h,authenticated=True,standalone=False)
  page.wait_for_timeout(120)
  if page.locator('.pwa-update-prompt').count():page.locator('.pwa-update-later').click()
  page.locator('.nav button[data-view="clients"]').click();page.wait_for_timeout(90)
  page.locator('.client-row .client-open-indicator').first.click();page.wait_for_selector('#clientEditor');page.wait_for_timeout(100)
  check(page.locator('.glass-client-actions').count()==0,f'{w}: desktop has no duplicate injected client action bar')
  actions=page.locator('#clientEditor .client-quick-actions')
  action_box=actions.bounding_box(); display=actions.evaluate("el=>getComputedStyle(el).display")
  child_boxes=page.locator('#clientEditor .client-quick-actions-v245 > *:visible').evaluate_all('els=>els.map(el=>el.getBoundingClientRect())')
  rows=sorted({round(r['y']) for r in child_boxes}) if child_boxes else []
  check(display=='grid' and action_box is not None and len(rows)<=2,f'{w}: native desktop client actions remain compact without orphan layout')
  header_box=page.locator('#clientEditor>header').bounding_box()
  check(header_box is not None and header_box['height']<190,f'{w}: desktop client header cannot balloon from actions')
  card_box=page.locator('.modal-card:has(.client-card-form)').bounding_box()
  check(card_box is not None and card_box['x']>=12 and card_box['x']+card_box['width']<=w-12,f'{w}: desktop client card uses the viewport without clipping')
  preview=page.locator('#clientDocumentPreview')
  preview.evaluate("""el=>{el.className='client-document-preview preview-unavailable';el.innerHTML='<div class="document-private-badge">Приватний документ</div><img hidden alt="Фото документа клієнта"><div class="document-preview-meta"><div><b>MG_5195.jpeg</b><span>Формат фото не підтримує попередній перегляд у цьому браузері — відкрийте файл кнопкою.</span></div><a class="btn subtle" href="#">Відкрити фото</a></div>'}""")
  badge_box=preview.locator('.document-private-badge').bounding_box();meta_box=preview.locator('.document-preview-meta').bounding_box();open_box=preview.locator('.document-preview-meta .btn').bounding_box();decoration=preview.locator('.document-preview-meta .btn').evaluate("el=>getComputedStyle(el).textDecorationLine")
  check(badge_box is not None and meta_box is not None and badge_box['y']+badge_box['height']<=meta_box['y']+1,f'{w}: desktop private-document badge stays above fallback content without overlap')
  check(open_box is not None and open_box['height']>=42 and open_box['width']>=130,f'{w}: desktop open-document action has deliberate button geometry')
  check(decoration=='none',f'{w}: desktop open-document action does not fall back to underline styling')
  columns=page.locator('.client-card-grid-v245').evaluate("el=>getComputedStyle(el).gridTemplateColumns.split(' ').length")
  check(columns==2,f'{w}: desktop client card keeps the agreed two-column contacts/history core')
  check(mod.no_overflow(page),f'{w}: desktop client card creates no horizontal overflow')
  if w==1440: page.screenshot(path=str(ROOT/'glass-test-results/client-card-glass-v4-desktop-1440.png'),full_page=True)
  page.close()
 browser.close()
if fail:
 print(f'\nFAILED {len(fail)} checks')
 for item in fail: print(' - '+item)
 raise SystemExit(1)
print('\nFULL GLASS V4 QA GREEN')
